[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=13.3"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=13.3"]

[target.aarch64-pc-windows-gnu]
rustflags = ["-C", "force-frame-pointers=yes"]
