#![allow(unused)]
#![allow(unsafe_op_in_unsafe_fn)]

/* automatically generated by rust-bindgen 0.72.1 */

#[repr(u32)]
#[doc = " @brief The Result type the API returns for giving feedback about the success\n or error of a called function"]
#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub enum UnHEICBridgeResult {
    Success = 1,
    #[doc = " The function finished executing successfully"]
    ReadingInputImageFailed = 2,
    #[doc = " The HEIC/HEIF input could not be read"]
    InvalidUnHEICCXXImageHandle = 4,
    #[doc = " The UnHEICCXXImageHandle is invalid or not initialized"]
    ImageNoInterleavedChannel = 8,
    #[doc = " The HEIC/HEIF image has no interleaved channel to read from"]
    InvalidImageDimensions = 16,
}
#[doc = " @brief An opaque handle for Rust to temporarily take ownership of data\n which is handled by C++\n\n @warning This type needs a manual Rust Drop implementation, because it has\n a C++ destructor."]
#[repr(C)]
#[repr(align(8))]
#[derive(Debug)]
pub struct UnHEICCXXImageHandle {
    pub _bindgen_opaque_blob: [u64; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UnHEICCXXImageHandle"][::std::mem::size_of::<UnHEICCXXImageHandle>() - 16usize];
    ["Alignment of UnHEICCXXImageHandle"][::std::mem::align_of::<UnHEICCXXImageHandle>() - 8usize];
};
impl UnHEICCXXImageHandle {
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        UnHEICCXXImageHandle_UnHEICCXXImageHandle(__bindgen_tmp.as_mut_ptr());
        __bindgen_tmp.assume_init()
    }
    #[inline]
    pub unsafe fn destruct(&mut self) {
        UnHEICCXXImageHandle_UnHEICCXXImageHandle_destructor(self)
    }
}
unsafe extern "C" {
    #[doc = " The internal libheif image. Needs to be released on destruction."]
    #[link_name = "\u{1}__ZN20UnHEICCXXImageHandleC1Ev"]
    pub fn UnHEICCXXImageHandle_UnHEICCXXImageHandle(this: *mut UnHEICCXXImageHandle);
    #[doc = " The constructor which initializes an empty handle"]
    #[link_name = "\u{1}__ZN20UnHEICCXXImageHandleD1Ev"]
    pub fn UnHEICCXXImageHandle_UnHEICCXXImageHandle_destructor(this: *mut UnHEICCXXImageHandle);
    #[doc = " @brief Attempts to read an input HEIF/HEIC file, decode it and store it in\n        the provided opaque handle\n\n @param [in] path The path to the HEIC/HEIF file\n @param [out] out_handle A pre-allocated handle for storing the resulting\n              image data. Only for use within C++ and therefore opaque to\n              Rust.\n\n @note This function is safe to be called from any thread.\n\n @return A status code indicating whether the function executed successfully"]
    pub fn heic_read_input_image(
        path: *const ::std::os::raw::c_char,
        out_handle: *mut UnHEICCXXImageHandle,
    ) -> UnHEICBridgeResult;
    #[doc = " @brief Gets the image dimensions of a previously read HEIC/HEIF image\n\n @param [in] image_handle The handle to the previously read image\n @param [out] width The width of the image in pixels\n @param [out] height The height of the image in pixels\n\n @note This function is safe to be called from any thread.\n\n @return A status code indicating whether the function executed successfully"]
    pub fn heic_get_image_dimensions(
        image_handle: *const UnHEICCXXImageHandle,
        width: *mut usize,
        height: *mut usize,
    ) -> UnHEICBridgeResult;
    #[doc = " @brief Gets the image RGBA data of a previously read HEIC/HEIF image as\n        read-only bytes\n\n @param [in] image_handle The handle to the previously read image\n @param [in] width The width of the image in pixels\n @param [in] height The height of the image in pixels\n @param [out] stride The stride of the image (i.e, row width in bytes)\n @param [out] ro_rgba_data A pointer to the read-only RGBA image data\n\n @note This function is safe to be called from any thread.\n\n @warning This function only succeeds if the passed in width and height\n          matches the actual image width and height. It serves as a a sanity\n          check.\n\n @warning The ro_rgba_data has a a lifetime that matches the input\n          const UnHEICCXXImageHandle& image_handle.\n\n @return A status code indicating whether the function executed successfully"]
    pub fn heic_get_image_data_rgba(
        image_handle: *const UnHEICCXXImageHandle,
        width: *const usize,
        height: *const usize,
        stride: *mut usize,
        ro_rgba_data: *mut *const u8,
    ) -> UnHEICBridgeResult;
    #[doc = " @brief Returns the number of bytes required to store a single pixel of this\n        input image\n\n @param [in] image_handle The handle to the previously read image\n @param [out] nb_bytes The number of bytes per pixel\n\n @note This function is safe to be called from any thread.\n\n @return A status code indicating whether the function executed successfully"]
    pub fn heic_get_bytes_per_pixel(
        image_handle: *const UnHEICCXXImageHandle,
        nb_bytes: *mut usize,
    ) -> UnHEICBridgeResult;
}
